version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - OAUTH_GITHUB_SECRET
      - SESSION_SECRET
      - NODE_ENV
  redis:
    image: "redis"
    volumes:
      - redis_data:/data
  postgres:
    image: "postgres"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
volumes:
  redis_data:
  pgdata:
