version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  redis:
    image: "redis"
    volumes:
      - redis_data:/data
  postgres:
    image: "postgres"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  redis_data:
  pgdata:
